from __future__ import annotations

from pathlib import Path
from typing import Any
import re

from src.agents.base_agent import BaseAgent
from src.tools.tool_registry import ToolRegistry


class CodingAgent(BaseAgent):
    name = "CodingAgent"

    def __init__(self, tools: ToolRegistry, repo_root: Path | None = None):
        self.tools = tools
        self.repo_root = repo_root or Path(__file__).resolve().parents[2]

    async def plan(self, task: dict[str, Any]) -> dict[str, Any]:
        desc = str(task.get("description") or "").lower()
        capability = "general_code"
        if "react" in desc or "component" in desc:
            capability = "react_component"
        elif "endpoint" in desc or "api" in desc:
            capability = "api_endpoint"
        elif "bug" in desc or "fix" in desc:
            capability = "bug_fix"
        return {
            "agent": self.name,
            "strategy": "code_generation",
            "targets": ["python", "react", "api"],
            "capability": capability,
            "task": task,
        }

    @staticmethod
    def _slug(name: str, default: str = "module") -> str:
        n = re.sub(r"[^a-z0-9_]+", "_", (name or "").strip().lower())
        n = re.sub(r"_+", "_", n).strip("_")
        return n or default

    async def generate_python_module(self, module_name: str, description: str) -> dict[str, Any]:
        modules_dir = self.repo_root / "src" / "tools" / "generated"
        modules_dir.mkdir(parents=True, exist_ok=True)
        slug = self._slug(module_name, default="generated_module")
        module_path = modules_dir / f"{slug}.py"

        code = (
            "from __future__ import annotations\n\n"
            "from typing import Any\n\n"
            f"class Tool:\n"
            f"    name = \"{slug}\"\n"
            f"    description = \"{description.strip() or 'Autogenerated capability module'}\"\n\n"
            "    async def run(self, **kwargs: Any) -> dict[str, Any]:\n"
            "        return {\"status\": \"success\", \"tool\": self.name, \"kwargs\": kwargs}\n\n"
            "tool = Tool()\n"
        )
        module_path.write_text(code, encoding="utf-8")
        await self.tools.reload()
        return {"status": "success", "path": str(module_path), "tool": slug}

    async def generate_react_component(self, component_name: str, description: str) -> dict[str, Any]:
        ui_dir = self.repo_root / "frontend" / "src" / "generated"
        ui_dir.mkdir(parents=True, exist_ok=True)
        safe_name = "".join(ch for ch in (component_name or "GeneratedPanel") if ch.isalnum()) or "GeneratedPanel"
        file_path = ui_dir / f"{safe_name}.tsx"

        code = (
            "import React from 'react';\n\n"
            f"type {safe_name}Props = {{\n"
            "  title?: string;\n"
            "};\n\n"
            f"export default function {safe_name}(props: {safe_name}Props) {{\n"
            f"  const title = props.title ?? '{description.strip() or safe_name}';\n"
            "  return (\n"
            "    <section style={{ padding: '1rem', border: '1px solid #ddd', borderRadius: '0.75rem' }}>\n"
            "      <h3 style={{ margin: 0 }}>{title}</h3>\n"
            "      <p style={{ marginTop: '0.5rem' }}>Generated by Jarvis CodingAgent.</p>\n"
            "    </section>\n"
            "  );\n"
            "}\n"
        )
        file_path.write_text(code, encoding="utf-8")
        return {"status": "success", "path": str(file_path), "component": safe_name}

    async def generate_api_endpoint(self, endpoint_name: str, description: str) -> dict[str, Any]:
        api_dir = self.repo_root / "src" / "api" / "generated"
        api_dir.mkdir(parents=True, exist_ok=True)
        slug = self._slug(endpoint_name, default="endpoint")
        file_path = api_dir / f"{slug}_route.py"

        code = (
            "from __future__ import annotations\n\n"
            "from fastapi import APIRouter\n\n"
            "router = APIRouter()\n\n"
            f"@router.get('/generated/{slug}')\n"
            "async def generated_endpoint() -> dict:\n"
            "    return {\n"
            f"        'status': 'ok',\n"
            f"        'endpoint': '{slug}',\n"
            f"        'description': '{description.strip() or 'Generated endpoint'}',\n"
            "    }\n"
        )
        file_path.write_text(code, encoding="utf-8")
        return {"status": "success", "path": str(file_path), "endpoint": f"/generated/{slug}"}

    async def propose_bug_fix(self, task: dict[str, Any]) -> dict[str, Any]:
        target_file = str(task.get("target_file") or "")
        issue = str(task.get("issue") or task.get("description") or "bug report")
        return {
            "status": "success",
            "agent": self.name,
            "mode": "bug_fix",
            "target_file": target_file,
            "analysis": f"Generated bug-fix analysis for: {issue}",
            "next_action": "Provide concrete patch instructions to apply in source tree.",
        }

    async def generate_tool_module(self, capability_name: str, description: str) -> dict[str, Any]:
        tools_dir = self.repo_root / "src" / "tools"
        tools_dir.mkdir(parents=True, exist_ok=True)
        file_name = f"{capability_name.strip().lower().replace(' ', '_')}_tool.py"
        module_path = tools_dir / file_name

        class_name = "Tool"
        code = (
            "from __future__ import annotations\n\n"
            "from typing import Any\n\n"
            f"class {class_name}:\n"
            f"    name = \"{capability_name.strip().lower().replace(' ', '_')}\"\n"
            f"    description = \"{description.strip()}\"\n\n"
            "    async def run(self, **kwargs: Any) -> dict[str, Any]:\n"
            "        return {\"status\": \"success\", \"tool\": self.name, \"args\": kwargs}\n\n"
            "tool = Tool()\n"
        )
        module_path.write_text(code, encoding="utf-8")
        await self.tools.reload()
        return {"status": "success", "tool_module": str(module_path)}

    async def execute(self, task: dict[str, Any]) -> dict[str, Any]:
        desc = str(task.get("description") or "")
        if "generate tool" in desc.lower() or task.get("generate_tool"):
            capability = str(task.get("capability") or "dynamic_capability")
            return await self.generate_tool_module(capability, desc or "Autogenerated Jarvis tool")

        if task.get("generate_python"):
            return await self.generate_python_module(
                str(task.get("module_name") or task.get("title") or "generated_module"),
                desc,
            )

        if task.get("generate_react"):
            return await self.generate_react_component(
                str(task.get("component_name") or task.get("title") or "GeneratedPanel"),
                desc,
            )

        if task.get("generate_api"):
            return await self.generate_api_endpoint(
                str(task.get("endpoint_name") or task.get("title") or "endpoint"),
                desc,
            )

        if task.get("fix_bug"):
            return await self.propose_bug_fix(task)

        return {
            "status": "success",
            "agent": self.name,
            "summary": "Coding workflow completed (Python/React/API path available).",
        }

    async def evaluate(self, task: dict[str, Any], execution_result: dict[str, Any]) -> dict[str, Any]:
        ok = str(execution_result.get("status") or "").lower() == "success"
        return {
            "agent": self.name,
            "task_id": task.get("task_id"),
            "status": "pass" if ok else "fail",
            "reason": execution_result.get("error") if not ok else None,
        }
